debian/control: Add dependency on rustc-1.82
One of our dependencies now depends on rustc-1.81:

    error: package `time v0.3.43` cannot be built because it requires rustc 1.81.0 or newer, while the currently active rustc version is 1.75.0

Fortunately, rustc-1.81 is packaged in Noble - and even rustc-1.82 is!
So let's use that to build our Rust code.