locking: Return ErrLockTimeout on EINTR
We've seen the test fail in the CI with:

    Error Trace: /home/runner/work/authd/authd/internal/users/locking/locking_bwrap_test.go:266
    Error:       Target error should be in err chain:
                 expected: "failed to lock the shadow password database: timeout"
                 in chain: "failed to lock the shadow password database: Interrupted system call"
    Test:        TestLockingLockedDatabaseFailsAfterTimeout

The reason is probably that the alarm set by lckpwdf does sometimes
work in the CI, so lckpwdf returns an error before our own 16 second
timeout is reached, resulting in a different error to be returned.

Return a ErrLockTimeout when that happens.