pam/integration-tests/ssh: Drop our safeBuffer implementation
It seems that new go runtime fixed it, in fact the last vulnerability
fix mentions the code using it:

Vulnerability #1: GO-2025-3563
    Request smuggling due to acceptance of invalid chunked data in net/http
  More info: https://pkg.go.dev/vuln/GO-2025-3563
  Standard library
    Found in: net/http/internal@go1.23.6
    Fixed in: net/http/internal@go1.23.8
    Example traces found:
Error:       #1: pam/integration-tests/ssh_test.go:618:27:
             integration.safeBuffer.ReadFrom calls bytes.Buffer.ReadFrom,
             hich eventually calls internal.chunkedReader.Read

Anyways even if that isn't fully related, -race works fine without it now,
so drop unneeded code