Try fixing flaky TestUserByIDAndName/Successfully_get_a_user_by_ID
The test was flaky, it sometimes failed with:

    ❌ TestUserByIDAndName/Successfully_get_a_user_by_ID (10ms)
          tempentries_test.go:138:
              	Error Trace:	/home/runner/work/authd-private/authd-private/internal/users/tempentries/tempentries_test.go:138
              	Error:      	Received unexpected error:
              	            	checking UID and name uniqueness: getpwent: Invalid argument
              	Test:       	TestUserByIDAndName/Successfully_get_a_user_by_ID
              	Messages:   	RegisterUser should not return an error, but did

We suspect that's because something else is writing errno. Let's try if
running the test non-parallel fixes it.