Bump Go version to 1.24
Required by golang.org/x/sys@v0.31.0 and golang.org/x/net@v0.36.0:

    Error: /home/runner/go/pkg/mod/golang.org/x/sys@v0.31.0/unix/vgetrandom_linux.go:7:9: file requires newer Go version go1.24 (application built with go1.23)
    Error: /home/runner/go/pkg/mod/golang.org/x/net@v0.36.0/http2/config_go124.go:7:9: file requires newer Go version go1.24 (application built with go1.23)